import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getLocation } from "@/actions/get-location";
import { getCategories } from "@/actions/get-categories";
import Header from "@/components/layouts/header";

const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin", "vietnamese"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const location = await getLocation();
    const categories = await getCategories();
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={openSans.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <Header location={location} categories={categories} />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
